DATA:
  dataset: "trot_1_goal_10_sol"
  data_dir: "/home/atari_ws/data/"
  batch_size: 32
  return_index: True
  augmentation: False
  shuffle: True
  normalize: False

MODEL:
  model_name: CDCDTransformerConditionedBase2
  PARAMS: # arguments that will be passed to the chosen models
    timesteps: 50
    learn_snr: False
    output_length: 8
    exclude_first: 14
    hidden_dim: 64
    n_layers: 3
    num_heads: 4
    dropout: 0.2
    self_conditioning: False
    beta_start: 1.0e-3
    beta_end: 0.4
    beta_schedule: scaled_linear
    prediction_type: sample

TRAINING: # arguments that will be passed to the trainer
  criterion_str: CrossEntropyLoss
  optimizer:
    optimizer_name: AdamW
    PARAMS:
      lr: 0.0001
      weight_decay: 1.0e-5
  epochs: 1000
  logdir: "./logs/CDCD_Transformer/trot_1_goal_10_sol"
  use_logger: True
  train_test_ratio: 15
  # ema_power: 0.99

# SWEEP: # arguments to sweep over and their values
#   latent_dim: [32, 64]
#   points_per_circle:
#     min: 3
#     max: 10
#     n: 3
#   lr:
#     min: 0.0001
#     max: 0.001
#     n: 2
#     logspace: True