DATA:
  dataset: "diagonal_2plans_rand"
  data_dir: "/home/victor/Datasets/ESFAL/"
  batch_size: 32
  return_index: True
  augmentation: False
  shuffle: False
  noise_level: 0.0

MODEL:
  model_name: CDCDTransformerConditioned2
  PARAMS: # arguments that will be passed to the chosen models
    timesteps: 50
    learn_snr: False
    output_length: 8
    exclude_first: 10
    hidden_dim: 128
    n_layers: 4
    beta_schedule: sigmoid
    beta_end: 0.05
    num_heads: 8
    dropout: 0.1
    prediction_type: "sample"
    self_conditioning: True
    ema_power: 0.75
    gradient_clipping: 0.1


TRAINING: # arguments that will be passed to the trainer
  criterion_str: CrossEntropyLoss
  optimizer:
    optimizer_name: AdamW
    PARAMS:
      lr: 0.0005
      weight_decay: 1.0e-5
  epochs: 500
  logdir: "./logs/CDCD_TransformerMean/diagonal_2plans_rand"
  use_logger: True
  train_test_ratio: 15

# SWEEP: # arguments to sweep over and their values
#   latent_dim: [32, 64]
#   points_per_circle:
#     min: 3
#     max: 10
#     n: 3
#   lr:
#     min: 0.0001
#     max: 0.001
#     n: 2
#     logspace: True