DATA:
  name: MCTSDataset
  PARAMS:
    exp_dir: "/home/atari_ws/data/jump/train"
    batch_size: 32
    shuffle_period: 0
    ddpm: True

MODEL:
  name: AttentionConditionalUnet1D
  PARAMS: # arguments that will be passed to the chosen models
    timesteps: 50
    input_dim: 3
    embedding_dim: 3
    diffusion_step_embed_dim: 32
    down_dims: {32, 64, 128}
    kernel_size: 3
    num_heads: 1
    exclude_first: 14
    beta_start: 1.0e-3
    beta_end: 0.3
    beta_schedule: scaled_linear
    prediction_type: epsilon

TRAINER: # arguments that will be passed to the trainer
  name: "ddpm"
  PARAMS:
    criterion_str: MSELoss
    optimizer:
      optimizer_name: AdamW
      PARAMS:
        lr: 5.0e-4
        weight_decay: 1.0e-5
    epochs: 1000
    logdir: "./logs/UNet_DDPM/jump/"
    use_logger: True