DATA:
  dataset: "diagonal_2plans_rand"
  data_dir: "/home/victor/Datasets/ESFAL/"
  batch_size: 64
  return_index: False
  augmentation: False
  shuffle: True
  noise_level: 0.0

MODEL:
  model_name: TransformerConditioned
  PARAMS: # arguments that will be passed to the chosen models
    timesteps: 50
    output_length: 8
    exclude_first: 10
    hidden_dim: 128
    n_layers: 4

TRAINING: # arguments that will be passed to the trainer
  criterion_str: MSELoss
  optimizer:
    optimizer_name: AdamW
    PARAMS:
      lr: 0.0005
      weight_decay: 1.0e-6
  epochs: 150
  logdir: "./logs/DDPM_Transformer/diagonal_2plans_rand"
  use_logger: True
  lr_scheduler:
    lr_scheduler_name: ExponentialLR
    PARAMS:
      gamma: 0.98

# SWEEP: # arguments to sweep over and their values
#   latent_dim: [32, 64]
#   points_per_circle:
#     min: 3
#     max: 10
#     n: 3
#   lr:
#     min: 0.0001
#     max: 0.001
#     n: 2
#     logspace: True