DATA: # arguments that will be passed to get_dataloaders
  dataset: diagonal_2plans_rand
  data_dir: "/home/victor/Datasets/ESFAL/"
  batch_size: 64
  return_index: False
  augmentation: False
  shuffle: True
  noise_level: 0.0

MODEL:
  model_name: AttentionConditionalUnet1D
  PARAMS: # arguments that will be passed to the chosen models
    timesteps: 50
    learn_snr: False
    prediction_type: "sample"
    input_dim: 3
    embedding_dim: 3
    diffusion_step_embed_dim: 64
    down_dims: {64, 128, 256}
    beta_schedule: "sigmoid"
    beta_end: 0.1
    kernel_size: 3
    exclude_first: 10
    num_heads: 1
    ema_power: 0.75

TRAINING: # arguments that will be passed to the trainer
  criterion_str: MSELoss
  optimizer:
    optimizer_name: AdamW
    PARAMS:
      lr: 0.0005
      weight_decay: 1.0e-6
  epochs: 500
  logdir: "./logs/AttentionDDPMLearnNoise/diagonal_2plans_rand"
  use_logger: True
  train_test_ratio: 15
