DATA:
  name: MCTSDataset
  PARAMS:
    exp_dir: "/home/atari_ws/data/jump/train"
    batch_size: 32
    shuffle_period: 0

MODEL:
  name: MLP
  PARAMS: # arguments that will be passed to the chosen models
    input_dim: 285
    output_dim: 24
    n_hidden: 3
    latent_dim: 128
    dropout: 0.3

TRAINER: # arguments that will be passed to the trainer
  name: "supervised"
  PARAMS:
    criterion_str: MSELoss
    optimizer:
      optimizer_name: Adam
    lr: 5.0e-4
    epochs: 2000
    logdir: "./logs/MLP/jump"
    use_logger: True