DATA:
  dataset: "trot_grid"
  data_dir: "/home/atari_ws/data/"
  batch_size: 1024
  return_index: True
  augmentation: False
  shuffle: False

MODEL:
  model_name: ConditionalMLP_CDCD
  PARAMS: # arguments that will be passed to the chosen models
    timesteps: 200
    diffusion_step_embed_dim: 128
    input_dim: 3
    output_dim: 81
    latent_dim: 256
    n_hidden: 3
    exclude_first: 14
    beta_start: 1.0e-4
    beta_end: 0.3
    beta_schedule: scaled_linear
    prediction_type: sample

TRAINING: # arguments that will be passed to the trainer
  criterion_str: CrossEntropyLoss
  optimizer:
    optimizer_name: Adam
  lr: 0.0001
  epochs: 1000
  logdir: "./logs/MLP_CDCD/trot_grid"
  use_logger: True
  # lr_scheduler:
  #   lr_scheduler_name: ExponentialLR
  #   PARAMS:
  #     gamma: 0.98

# SWEEP: # arguments to sweep over and their values
#   latent_dim: [32, 64]
#   points_per_circle:
#     min: 3
#     max: 10
#     n: 3
#   lr:
#     min: 0.0001
#     max: 0.001
#     n: 2
#     logspace: True