DATA:
  dataset: "diagonal_2plans_rand"
  data_dir: "/home/victor/Datasets/ESFAL/"
  batch_size: 32
  return_index: False
  augmentation: False
  shuffle: True
  noise_level: 0.0

MODEL:
  model_name: MLP
  PARAMS: # arguments that will be passed to the chosen models
    input_dim: 273
    output_dim: 24
    n_hidden: 4
    latent_dim: 64

TRAINING: # arguments that will be passed to the trainer
  criterion_str: MSELoss
  optimizer:
    optimizer_name: Adam
  lr: 0.001
  epochs: 500
  logdir: "./logs/MLP/diagonal_2plans_rand"
  use_logger: True
  lr_scheduler:
    lr_scheduler_name: ExponentialLR
    PARAMS:
      gamma: 0.9955

# SWEEP: # arguments to sweep over and their values
#   latent_dim: [32, 64]
#   points_per_circle:
#     min: 3
#     max: 10
#     n: 3
#   lr:
#     min: 0.0001
#     max: 0.001
#     n: 2
#     logspace: True